// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/5/2024, 1:25:12 AM
const configMerger = require("/home/joaquin/joaquin-blog/joaquin-blog/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/joaquin/joaquin-blog/joaquin-blog/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/home/joaquin/joaquin-blog/joaquin-blog/layouts/**/*.{vue,js,mjs}","/home/joaquin/joaquin-blog/joaquin-blog/pages/**/*.{vue,js,mjs}","/home/joaquin/joaquin-blog/joaquin-blog/composables/**/*.{js,ts,mjs}","/home/joaquin/joaquin-blog/joaquin-blog/utils/**/*.{js,ts,mjs}","/home/joaquin/joaquin-blog/joaquin-blog/{A,a}pp.{vue,js,mjs}","/home/joaquin/joaquin-blog/joaquin-blog/{E,e}rror.{vue,js,mjs}","/home/joaquin/joaquin-blog/joaquin-blog/app.config.{js,ts,mjs}"] }));

module.exports = config
