// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/26/2024, 10:46:00 PM
const configMerger = require("/home/joaquin/Source/joaquin-blog/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/joaquin/Source/joaquin-blog/components/**/*.{vue,js,mjs}","components/**/*.{vue,js,mjs}","/home/joaquin/Source/joaquin-blog/layouts/**/*.{vue,js,mjs}","/home/joaquin/Source/joaquin-blog/pages/**/*.{vue,js,mjs}","/home/joaquin/Source/joaquin-blog/composables/**/*.{js,ts,mjs}","/home/joaquin/Source/joaquin-blog/utils/**/*.{js,ts,mjs}","/home/joaquin/Source/joaquin-blog/{A,a}pp.{vue,js,mjs}","/home/joaquin/Source/joaquin-blog/{E,e}rror.{vue,js,mjs}","/home/joaquin/Source/joaquin-blog/app.config.{js,ts,mjs}"] }));

module.exports = config
